import torch
import torchaudio

def test_normalization():
    # 1. Load Original Audio
    orig, sr_orig = torchaudio.load("speaker.wav")
    
    # 2. Load Protected Audio (generated by CloneShield)
    prot, sr_prot = torchaudio.load("speaker_protected.wav")
    
    # Truncate to min length
    min_len = min(orig.shape[-1], prot.shape[-1])
    orig = orig[:, :min_len]
    prot = prot[:, :min_len]
    
    # The perturbation before XTTS touches it
    diff_raw = torch.abs(orig - prot)
    print(f"RAW perturbation max: {diff_raw.max().item():.6f}")
    
    # 3. Apply XTTS's internal normalization logic
    # As seen in `get_conditioning_latents`: if sound_norm_refs: audio = (audio / torch.abs(audio).max()) * 0.75
    orig_xtts = (orig / torch.abs(orig).max()) * 0.75
    prot_xtts = (prot / torch.abs(prot).max()) * 0.75
    
    # The perturbation AFTER XTTS normalizes both independently
    diff_xtts = torch.abs(orig_xtts - prot_xtts)
    print(f"XTTS-NORMALIZED perturbation max: {diff_xtts.max().item():.6f}")
    
    # Let's compare the magnitude of the perturbation vs the signal itself
    print(f"\nSignal max (orig): {orig.abs().max().item():.6f}")
    print(f"Signal max (prot): {prot.abs().max().item():.6f}")
    
    print("\nIf 'XTTS-NORMALIZED perturbation max' is tiny compared to RAW, then XTTS is erasing our noise by re-scaling the two files differently.")

if __name__ == "__main__":
    test_normalization()
